siteName: poko demo
logo: ""
htmlHead: |-
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Questrial&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="/ctx.css"> <link rel="stylesheet" href="/local.css">
languages:
  - code: fr
    name: Français
    status: published
    isCmsDefault: false
    isWebsiteDefault: false
  - code: en
    name: English
    status: published
    isCmsDefault: false
    isWebsiteDefault: false
collections:
  - articles
metadata:
  image: ""
