siteName: poko demo
logo: /_images/POKO-logo-RVB-01.jpg
htmlHead: |-
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/m4rrc0/ctx-css@c/una-scelta/dist/index.css">
  <link rel="stylesheet" href="/local.css">
languages:
  - code: fr
    name: Français
    status: published
    isCmsDefault: false
    isWebsiteDefault: false
  - code: en
    name: English
    status: published
    isCmsDefault: false
    isWebsiteDefault: false
collections:
  - articles
metadata:
  image: ""
