siteName: poko demo
productionUrl: https://m4rrc0.github.io/poko-website-builder
logo: /_images/POKO-logo-RVB-01.jpg
htmlHead: |-
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/m4rrc0/ctx-css@c/una-scelta/dist/index.css">
  <link rel="stylesheet" href="/local.css">
collections:
  - articles
metadata:
  image: ""
